=== zlubsen/dis-rs/dis-rs/definitions/v8-schemas/DISsyntax.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2025 by the Simulation Interoperability Standards Organization, Inc.
SISO Inc. Board of Directors
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
All rights reserved.

Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
make derivative works from this material, for all purposes, provided that any use of the material
contains the following attribution: Reprinted with permission from SISO Inc. Should
a reader require additional information, contact the SISO Inc. Board of Directors.

Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
display, and make derivative works from this material, for noncommercial purposes, provided that
any use of the material contains the following attribution: Reprinted with permission from SISO Inc. 
The material may not be used for a commercial purpose without express written
permission from the SISO Inc Board of Directors.

SISO Inc. Board of Directors
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
-->
<!--
     An XML schema for DIS PDUs and records, Version 8 and beyond, that exactly describe the binary
     on-the-wire syntax of a PDU for run-time processing.

     One intent is that Wireshark dissectors for DIS can be auto-generated from an XML file that
     conforms to this schema. The XML should contain all the information required by the dissector
     to create human-readable output of a captured PDU. To that end, all "name" and "type" attributes
     are human-readable and match the names in the DIS standard, including spaces and characters
     such as '/' and '-'.
     
     Another intent is to auto-generate marshalling code that creates and parses actual PDUs
     for on-the-wire sending and receiving. In that case, the "name" and "type" attributes would
     become variable names in the programming language used to implement the marshalling API
     and would not be allowed to have spaces and special characters. It is assumed that the
     code generator software can fix this either by replacing disallowed characters with an
     underscore or removing spaces to form a camel case variable name.

     The top-level elements are PDUs and records. They both contain sub-elements called fields.
     The order of the field elements in the PDU and records exactly matches on-the-wire ordering.
     PDUs contain simple fields, fixed-length records, and one set of extension records at the end.
     Records contain simple fields, other records, and arrays.

     Simple field types have no further definition in the XML document:
       - NumericField - integer or float, e.g. uint8, int32, float32
       - CountField - same as NumericField but limited to unsigned integers
       - EnumField - e.g. enum8, enum32. Enumerations can be looked up in SISO-REF-010.
       - FixedStringField - fixed-length character string
       - These three bit field types are used only in Bit Records
         - IntBitField
         - EnumBitField
         - BooleanBitField

     Record field types have further definition elsewhere in the XML document:
       - FixedRecordField - type matches a FixedRecord element
       - BitRecordField - type matches a BitRecord element or has a UID if defined in SISO-REF-010
       - AdaptiveRecordField - type matches an AdaptiveRecord element or has a UID if defined in SISO-REF-010

     Special elements
       - Array - repeating instance of a fixed type or fixed record preceded by a count field
       - VariableString - Variable length character string preceded by a uint8 or 16 count field
       - OpaqueData - Free fromat data preceded by a uint16 with the number of usable bits
       - PaddingTo64 - adds padding for 64-bit alignment at the end of Extension Records
       - PaddingTo8 and PaddingTo16 - adds padding to 8 or 16-bit boundary between variable types

     Extension Records are processed at run-time by matching the value of the Record Type
     field in the PDU to the value of the recordTypeEnum attribute in the XML document for that
     type of record.

     <PaddingTo64/> is a special element used to indicate that padding to a
     64-bit boundary may be necessary at the end of an Extension Record. The
     software using the XML to process run-time PDUs knows that the record starts on
     a 64-bit boundary so it is easy to calculate the length of the padding or to just
     merely skip to the end of the record since its length is known.

     <PaddingTo16/> and <PaddingTo32/> are similar, for use between multiple arrays,
     variable strings, or opaque data if necessary to make each starts on its required boundary.

     A BitRecord contains a total bit size attribute, which can be 8, 16, 32, or 64.
     Bit records can contain only these three field types:
       - IntBitField
       - EnumBitField
       - BooleanBitField
     All BitRecord fields have a required bitPosition attribute. The default value of the size
     attribute is 1 if not present. Missing bits are assumed to be Unused/Padding.

     Adaptive Records:
     Adaptive records have a variable format but a fixed length. An Adaptive Record allows
     one of several choices for the record format to be defined at run time. The choice is based on a
     discriminant whose run-time value determines the format of the record. The discriminant
     is an enumeration field that precedes the Adaptive Record. If the Adaptive Record is
     in an Extension Record, then the discriminant must precede the Adaptive Record in the
     same Extension Record.

     Limitations on field types following the rules of Clause 4.7 Data representation and enforced by the schema:

     PDUs can contain only fixed length fields (Numeric, Enum, FixedString, FixedRecord,
     BitRecord, AdaptiveRecord) and always end with a ExtensionRecordSet, which is an
     unsigned 16-bit Number Of Extension Records field followed by ExtensionRecordFields
     representing a set of Extension Records.

     Fixed records can contain only fixed-length fields: Numeric, Enum, FixedString, FixedRecord,
     BitRecord, AdaptiveRecord.

     The repeating element of an Array can be one of these fixed-length fields: Numeric, Enum, FixedString,
     FixedRecord, or BitRecord.

     Extension Records can contain any of the field types, including arrays, variable strings,
     and opaque data, but cannot contain another Extension Record. They always start with a
     16-bit Record Type enumeration field followed by a 16-bit unsigned integer Length field.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:annotation>
    <xs:documentation xml:lang="en">
      Distributed Interactive Simulation Protocol Syntax, Version 0.73, 29 December 2025
    </xs:documentation>
  </xs:annotation>

  <!--=== Primitives ===-->
  <xs:simpleType name="numeric_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="uint8"/>
      <xs:enumeration value="uint16"/>
      <xs:enumeration value="uint32"/>
      <xs:enumeration value="uint64"/>
      <xs:enumeration value="int8"/>
      <xs:enumeration value="int16"/>
      <xs:enumeration value="int32"/>
      <xs:enumeration value="int64"/>
      <xs:enumeration value="float32"/>
      <xs:enumeration value="float64"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="enum_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="enum8"/>
      <xs:enumeration value="enum16"/>
      <xs:enumeration value="enum32"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="count_t">
    <xs:restriction base="xs:string">
      <xs:enumeration value="uint8"/>
      <xs:enumeration value="uint16"/>
      <xs:enumeration value="uint32"/>
    </xs:restriction>
  </xs:simpleType>

  <!--=== Fields for Simple Types ===-->
  <xs:complexType name="numericField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="numeric_t" use="required"/>
    <xs:attribute name="units" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="countField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="count_t" use="required"/>
  </xs:complexType>

      <!-- UID reference is a STRING because it can be a range like "8, 14" or 223-234"-->
  <xs:complexType name="enumField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="enum_t" use="required"/>
    <xs:attribute name="enumTableUID" type="xs:string" use="optional"/>
    <xs:attribute name="hierarchyDependency" type="xs:string" use="optional"/>
    <xs:attribute name="isDiscriminant" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <xs:complexType name="fixedStringField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="length" type="xs:unsignedShort" use="required"/>
  </xs:complexType>

  <!--=== Fields for Bit Records ===-->
  <xs:complexType name="intBitField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="bitPosition" type="xs:byte" use="required"/>
    <xs:attribute name="size" type="xs:unsignedByte" use="optional"/>
    <xs:attribute name="units" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="enumBitField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="bitPosition" type="xs:byte" use="required"/>
    <xs:attribute name="size" type="xs:unsignedByte" use="optional"/>
    <xs:attribute name="enumTableUID" type="xs:string" use="optional"/>
    <xs:attribute name="isDiscriminant" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <xs:complexType name="booleanBitField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="bitPosition" type="xs:unsignedByte" use="required"/>
  </xs:complexType>

  <!--=== Fields for Records ===-->
  <xs:complexType name="fixedRecordField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="length" type="xs:unsignedShort" use="required"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="bitRecordField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="size" type="xs:unsignedShort" use="required"/>
    <!-- Either use type (if record is defined in this XML) or enumTableUID (if define in SISO-REF-010), but not both -->
    <!-- Can this be enforced in the schema? xs:choice works for elements, not attributes. -->
    <xs:attribute name="type" type="xs:string" use="optional"/>
    <xs:attribute name="enumTableUID" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="adaptiveRecordField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="length" type="xs:unsignedShort" use="required"/>
    <!-- Either use type (if record is defined in this XML) or enumTableUID (if define in SISO-REF-010), but not both -->
    <xs:attribute name="type" type="xs:string" use="optional"/>
    <xs:attribute name="enumTableUID" type="xs:string" use="optional"/>
    <xs:attribute name="discriminant" type="xs:string" use="required"/>
  </xs:complexType>

  <!--=== Fields for Special Types ===-->
  <xs:complexType name="variableStringField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="fixedNumberOfStrings" type="xs:unsignedShort" use="optional"/>
  </xs:complexType>

  <xs:complexType name="opaqueDataField_t">
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <!--=== Special Types ===-->
  <xs:complexType name="array_t">
    <xs:sequence>
      <xs:element name="CountField" type="countField_t"/>
      <xs:choice>
        <xs:element name="NumericField" type="numericField_t"/>
        <xs:element name="EnumField" type="enumField_t"/>
        <xs:element name="FixedStringField" type="fixedStringField_t"/>
        <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
        <xs:element name="BitRecordField" type="bitRecordField_t"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="variableString_t">
    <xs:sequence>
      <xs:element name="CountField" type="countField_t"/>
      <xs:element name="VariableStringField" type="variableStringField_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="opaqueData_t">
    <xs:sequence>
      <xs:element name="CountField" type="countField_t"/>
      <xs:element name="OpaqueDataField" type="opaqueDataField_t"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="adaptiveFormat_t">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="NumericField" type="numericField_t"/>
      <xs:element name="EnumField" type="enumField_t"/>
      <xs:element name="FixedStringField" type="fixedStringField_t"/>
      <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
      <xs:element name="BitRecordField" type="bitRecordField_t"/>
    </xs:choice>
    <xs:attribute name="discriminantStartValue" type="xs:unsignedInt" use="required"/>
  </xs:complexType>

 <!--=== Records ===-->
  <xs:complexType name="fixedRecord_t">
    <xs:choice minOccurs="2" maxOccurs="unbounded">
      <xs:element name="NumericField" type="numericField_t"/>
      <xs:element name="EnumField" type="enumField_t"/>
      <xs:element name="FixedStringField" type="fixedStringField_t"/>
      <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
      <xs:element name="BitRecordField" type="bitRecordField_t"/>
      <xs:element name="AdaptiveRecordField" type="adaptiveRecordField_t"/>
    </xs:choice>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="length" type="xs:unsignedShort"/>
  </xs:complexType>

  <xs:complexType name="bitRecord_t">
    <xs:choice minOccurs="1" maxOccurs="64">
      <xs:element name="EnumBitField" type="enumBitField_t"/>
      <xs:element name="IntBitField" type="intBitField_t"/>
      <xs:element name="BooleanBitField" type="booleanBitField_t"/>
    </xs:choice>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="size" type="xs:unsignedByte" use="required"/>
  </xs:complexType>

  <xs:complexType name="adaptiveRecord_t">
    <xs:sequence>
      <xs:element name="AdaptiveFormat" type="adaptiveFormat_t" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="length" type="xs:unsignedShort" use="required"/>
  </xs:complexType>

  <xs:complexType name="extensionRecordSet_t">
    <xs:sequence>
      <xs:element name="CountField" type="countField_t"/>
      <xs:element name="ExtensionRecordFields"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="extensionRecord_t">
    <xs:sequence>
      <xs:element name="EnumField" type="enumField_t"/>
      <xs:element name="NumericField" type="numericField_t"/>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="NumericField" type="numericField_t"/>
        <xs:element name="EnumField" type="enumField_t"/>
        <xs:element name="FixedStringField" type="fixedStringField_t"/>
        <xs:element name="VariableString" type="variableString_t"/>
        <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
        <xs:element name="BitRecordField" type="bitRecordField_t"/>
        <xs:element name="Array" type="array_t"/>
        <xs:element name="AdaptiveRecordField" type="adaptiveRecordField_t"/>
        <xs:element name="OpaqueData" type="opaqueData_t"/>
        <xs:element name="PaddingTo16"/>
        <xs:element name="PaddingTo32"/>
      </xs:choice>
      <xs:element name="PaddingTo64" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="recordTypeEnum" type="xs:unsignedShort" use="required"/>
    <xs:attribute name="baseLength" type="xs:unsignedShort" use="required"/>
    <xs:attribute name="isVariable" type="xs:boolean" use="required"/>
  </xs:complexType>

  <!--=== PDU ===-->
  <xs:complexType name="PDU_t">
    <xs:sequence>
      <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="NumericField" type="numericField_t"/>
        <xs:element name="EnumField" type="enumField_t"/>
        <xs:element name="FixedStringField" type="fixedStringField_t"/>
        <xs:element name="FixedRecordField" type="fixedRecordField_t"/>
        <xs:element name="BitRecordField" type="bitRecordField_t"/>
        <xs:element name="AdaptiveRecordField" type="adaptiveRecordField_t"/>
      </xs:choice>
      <xs:element name="ExtensionRecordSet" type="extensionRecordSet_t"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="PDUType" type="xs:unsignedByte" use="required"/>
    <xs:attribute name="protocolFamily" type="xs:unsignedByte" use="required"/>
    <xs:attribute name="baseLength" type="xs:unsignedShort" use="required"/>
  </xs:complexType>

  <!--=== Root Element ===-->
  <xs:element name="DISsyntax">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="copyright">
          <xs:annotation>
            <xs:documentation>Copyright statement.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element name="PDU" type="PDU_t"/>
          <xs:element name="FixedRecord" type="fixedRecord_t"/>
          <xs:element name="BitRecord" type="bitRecord_t"/>
          <xs:element name="AdaptiveRecord" type="adaptiveRecord_t"/>
          <xs:element name="ExtensionRecord" type="extensionRecord_t"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>Title of the document (e.g. SISO-REF-010-2010.1).</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="release" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>Release or version number (e.g. Draft 3, Final).</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="date" type="xs:date" use="required">
        <xs:annotation>
          <xs:documentation>Publication date specified in ISO 8601 date format (YYYY-MM-DD).</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="description" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>Description of the document.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="organization" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>Publishing organization.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== zlubsen/dis-rs/dis-rs/definitions/v8-schemas/DIS_Laser.xml
<?xml version="1.0" encoding="UTF-8"?>

<DISsyntax
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="DISsyntax.xsd"
  title="DIS Syntax Laser PDU"
  release="0.3"
  date="2025-12-29"
  description="Laser PDU and associated records. Conforms to 1278.1-202X Draft 5 and SISO-REF-030 Version 1.0."
  organization="Simulation Interoperability Standards Organization">

  <copyright><![CDATA[
Copyright © 2025 by the Simulation Interoperability Standards Organization, Inc.
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
All rights reserved.

Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
make derivative works from this material, for all purposes, provided that any use of the material
contains the following attribution: "Reprinted with permission from SISO Inc." Should
a reader require additional information, contact the SISO Inc. Board of Directors.

Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
display, and make derivative works from this material, for noncommercial purposes, provided that
any use of the material contains the following attribution: "Reprinted with permission from SISO Inc." 
The material may not be used for a commercial purpose without express written
permission from the SISO Inc Board of Directors.

SISO Inc. Board of Directors
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
]]></copyright>

  <PDU name="Laser" PDUType="24" protocolFamily="6" baseLength="32">
    <FixedRecordField name="PDU Header" length="16" type="PDU Header"/>
    <FixedRecordField name="Lasing Entity ID" length="6" type="Entity Identifier"/>
    <NumericField name="Laser System Number" type="uint8"/>
    <NumericField name="Number of Beams" type="uint8"/>
    <EnumField name="Laser System Name" type="enum16" enumTableUID="80" />
    <BitRecordField name="Attributes" size="8" type="Laser Attributes"/>
    <NumericField name="Padding" type="uint8"/>
    <NumericField name="Padding" type="uint16"/>
    <ExtensionRecordSet>
      <CountField name="Number Of Extension Records" type="uint16"/>
      <ExtensionRecordFields/>
    </ExtensionRecordSet>
  </PDU>

  <BitRecord type="Laser Attributes" size="8">
    <BooleanBitField name="Permanently Associated" bitPosition="0"/>
    <BooleanBitField name="Location Provided" bitPosition="1"/>
    <IntBitField name="Padding" bitPosition="2" size="6"/>
  </BitRecord>

  <ExtensionRecord name="Laser Beam" recordTypeEnum="6500" baseLength="88" isVariable="false">
    <EnumField name="Record Type" type="enum16" enumTableUID="99"/>
    <NumericField name="Record Length" type="uint16"/>
    <NumericField name="Beam ID" type="uint8"/>
    <BitRecordField name="Beam Status" size="8" type="Beam Status"/>
    <NumericField name="Beam Parameter Index" type="uint16"/>
    <NumericField name="Beam Code" type="uint16"/>
    <EnumField name="Beam Function" type="enum8" enumTableUID="883"/>
    <EnumField name="Beam Shape" type="enum8" enumTableUID="881"/>
    <EnumField name="Flash Pattern" type="enum8" enumTableUID="884"/>
    <NumericField name="Padding" type="uint8"/>
    <NumericField name="Padding" type="uint16"/>
    <NumericField name="Power" type="float32" units="Watts"/>
    <NumericField name="Wavelength" type="float32" units="microns"/>
    <NumericField name="Pulse Repetition Frequency" type="float32" units="Hertz"/>
    <NumericField name="Pulse Width" type="float32" units="microseconds"/>
    <NumericField name="Beamwidth" type="float32" units="radians"/>
    <NumericField name="Aperture" type="float32" units="meters"/>
    <FixedRecordField name="Beam Spot Location" length="24" type="World Coordinates"/>
    <FixedRecordField name="Illuminated Object ID" length="6" type="Entity Identifier"/>
    <EnumField name="Spot Type" type="enum8" enumTableUID="882"/>
    <EnumField name="Motion Pattern" type="enum8" enumTableUID="880"/>
    <FixedRecordField name="Beam Spot Offset with Respect to Illuminated Object" length="12" type="Entity Coordinate Vector"/>
    <NumericField name="Padding" type="uint32"/>
  </ExtensionRecord>

</DISsyntax>

=== zlubsen/dis-rs/dis-assemble-gen-3/definitions/v8-schemas/DIS_Acoustic.xml
<?xml version="1.0" encoding="UTF-8"?>

<DISsyntax
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="DISsyntax.xsd"
    title="DIS Syntax Acoustic PDU"
    release="0.3"
    date="2025-12-29"
    description="Acoustic PDU and associated records. Conforms to 1278.1-202X Draft 5 and SISO-REF-030 Version 1.0."
    organization="Simulation Interoperability Standards Organization">

    <copyright><![CDATA[
Copyright © 2025 by the Simulation Interoperability Standards Organization, Inc.
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
All rights reserved.

Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
make derivative works from this material, for all purposes, provided that any use of the material
contains the following attribution: "Reprinted with permission from SISO Inc." Should
a reader require additional information, contact the SISO Inc. Board of Directors.

Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
display, and make derivative works from this material, for noncommercial purposes, provided that
any use of the material contains the following attribution: "Reprinted with permission from SISO Inc."
The material may not be used for a commercial purpose without express written
permission from the SISO Inc Board of Directors.

SISO Inc. Board of Directors
7901 4th St N, Suite 300-4043
St. Petersburg, FL 33702
]]></copyright>

    <PDU name="Acoustic" PDUType="29" protocolFamily="6" baseLength="32">
        <FixedRecordField name="PDU Header" length="16" type="PDU Header"/>
        <FixedRecordField name="Emitting Entity ID" length="6" type="Entity Identifier"/>
        <NumericField name="Passive Parameter Index" type="uint16"/>
        <NumericField name="Padding" type="uint32"/>
        <BitRecordField name="Attributes" size="8" type="Acoustic Attributes"/>
        <BitRecordField name="Propulsion Plant Configuration" size="8" enumTableUID="149"/>
        <ExtensionRecordSet>
            <CountField name="Number Of Extension Records" type="uint16"/>
            <ExtensionRecordFields/>
        </ExtensionRecordSet>
    </PDU>

    <BitRecord type="Acoustic Attributes" size="8">
        <BooleanBitField name="Permanently Associated" bitPosition="0"/>
        <BooleanBitField name="Location Provided" bitPosition="1"/>
        <EnumBitField name="Origin of the Acoustic Emitter" bitPosition="2" size="2" enumTableUID="899"/>
        <IntBitField name="Padding" bitPosition="4" size="4"/>
    </BitRecord>

    <ExtensionRecord name="UA Shafts" recordTypeEnum="7000" baseLength="8" isVariable="true">
        <EnumField name="Record Type" type="enum16" enumTableUID="99"/>
        <NumericField name="Record Length" type="uint16"/>
        <NumericField name="Padding" type="uint16"/>
        <NumericField name="Padding" type="uint8"/>
        <Array>
            <CountField name="Number of Shafts" type="uint8"/>
            <FixedRecordField name="Shaft" length="8" type="Shaft"/>
        </Array>
    </ExtensionRecord>

    <FixedRecord type="Shaft" length="8">
        <NumericField name="Current Shaft RPM" type="int16" units="RPM"/>
        <NumericField name="Ordered Shaft RPM" type="int16" units="RPM"/>
        <NumericField name="Shaft RPM Rate of Change" type="int32" units="RPM/sec"/>
    </FixedRecord>

    <ExtensionRecord name="UA APA" recordTypeEnum="7001" baseLength="8" isVariable="true">
        <EnumField name="Record Type" type="enum16" enumTableUID="99"/>
        <NumericField name="Record Length" type="uint16"/>
        <NumericField name="Padding" type="uint16"/>
        <NumericField name="Padding" type="uint8"/>
        <Array>
            <CountField name="Number of APAs" type="uint8"/>
            <FixedRecordField name="APA" length="4" type="APA"/>
        </Array>
        <PaddingTo64/>
    </ExtensionRecord>

    <FixedRecord type="APA" length="4">
        <BitRecordField name="APA Parameter Index" size="16" type="APA Parameter Index"/>
        <NumericField name="APA Value" type="int16"/>
    </FixedRecord>

    <BitRecord type="APA Parameter Index" size="16">
        <EnumBitField name="APA Parameter" bitPosition="0" size="14" enumTableUID="150"/>
        <EnumBitField name="APA Status" bitPosition="14" size="2" enumTableUID="281"/>
    </BitRecord>

    <ExtensionRecord name="UA System" recordTypeEnum="7002" baseLength="24" isVariable="true">
        <EnumField name="Record Type" type="enum16" enumTableUID="99"/>
        <NumericField name="Record Length" type="uint16"/>
        <NumericField name="Acoustic System Number" type="uint8"/>
        <EnumField name="Emitter Status" type="enum8" enumTableUID="716"/>
        <NumericField name="Padding" type="uint16"/>
        <FixedRecordField name="Location with Respect to Entity" length="12" type="Entity Coordinate Vector"/>
        <EnumField name="Acoustic System Name" type="enum16" enumTableUID="144"/>
        <EnumField name="Function" type="enum8" enumTableUID="145"/>
        <Array>
            <CountField name="Number of Beams" type="uint8"/>
            <FixedRecordField name="UA Beam Parameter" length="24" type="UA Beam Parameter"/>
        </Array>
    </ExtensionRecord>

    <FixedRecord type="UA Beam Parameter" length="24">
        <NumericField name="Beam ID" type="uint8"/>
        <NumericField name="Padding" type="uint8"/>
        <NumericField name="Padding" type="uint16"/>
        <NumericField name="Active Emission Parameter Index" type="uint16"/>
        <EnumField name="Scan Pattern" type="enum16" enumTableUID="147"/>
        <NumericField name="Beam Center Azimuth" type="float32" units="radians"/>
        <NumericField name="Azimuthal Beamwidth" type="float32" units="radians"/>
        <NumericField name="Beam Center D/E" type="float32" units="radians"/>
        <NumericField name="D/E Beamwidth" type="float32" units="radians"/>
    </FixedRecord>

</DISsyntax>
